apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-attendance.fullname" . }}-backend
  labels:
    {{- include "ai-attendance.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      {{- if .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "ai-attendance.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
