# Values for Development Environment

backend:
  replicaCount: 1
  image:
    repository: hemantr1/ai-attendance-backend
  service:
    type: NodePort
  env:
    - name: ENV
      value: "development"
    - name: DEBUG
      value: "true"

frontend:
  replicaCount: 1
  image:
    repository: hemantr1/ai-attendance-frontend
  service:
    type: NodePort

ingress:
  enabled: true
  hosts:
    - host: dev.ai-attendance.local
      paths:
        - path: /
          pathType: Prefix
          backend: frontend
        - path: /api
          pathType: Prefix
          backend: backend
