# Values for Test Environment

backend:
  replicaCount: 2
  image:
    repository: hemantr1/ai-attendance-backend
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 8000
    nodePort: 30003
  env:
    ENV: "testing"
    DEBUG: "true"
    DATABASE_URL: "sqlite+aiosqlite:///./test.db"
    DATABASE_URL_SYNC: "sqlite:///./test.db"
    SECRET_KEY: "super-secret-key-change-me"
    ALLOWED_ORIGINS: '["*"]'

frontend:
  replicaCount: 2
  image:
    repository: hemantr1/ai-attendance-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
    nodePort: 30002

ingress:
  enabled: true
  hosts:
    - host: test.ai-attendance.com
      paths:
        - path: /
          pathType: Prefix
          backend: frontend
        - path: /api
          pathType: Prefix
          backend: backend
