# Values for Development Environment

backend:
  image:
    repository: hemantr1/ai-attendance-backend
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 8000
    nodePort: 30001
  env:
    ENV: "development"
    DEBUG: "true"
    DATABASE_URL: "sqlite+aiosqlite:///./test.db"
    DATABASE_URL_SYNC: "sqlite:///./test.db"
    SECRET_KEY: "super-secret-key-change-me"
    ALLOWED_ORIGINS: '["*"]'

frontend:
  image:
    repository: hemantr1/ai-attendance-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
    nodePort: 30000

ingress:
  enabled: true
  hosts:
    - host: dev.ai-attendance.local
      paths:
        - path: /
          pathType: Prefix
          backend: frontend
        - path: /api
          pathType: Prefix
          backend: backend
